spring:
  application:
    name: carro-micro
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  # Configuraciones de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    # spring.datasource.password=root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuraciones de JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect