#Este proyecto es un servidor el cual traera la configuracion de los de mas microservicios o se ha los clientes de un repositorio de github
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances #La rama donde esta la configuracion de los clientes(Proyectos)
          uri: https://github.com/ChristianGar2002/microservicios/
          search-paths: config-data #La carpeta donde estan los archivos de configuracion
  application:
    name: config-service

    # Configuraciones de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    # spring.datasource.password=root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuraciones de JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect